/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Farhan
 */
public class vFirst extends javax.swing.JFrame {

    /**
     * Creates new form vFirst
     */
    public vFirst() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(640, 480);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lSepotify = new javax.swing.JLabel();
        lMusicPlayer = new javax.swing.JLabel();
        bLogIn = new javax.swing.JButton();
        bSignUp = new javax.swing.JButton();
        lAlreadyHaveAnAccount = new javax.swing.JLabel();
        lNewUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 480));

        lSepotify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/iSepotify.png"))); // NOI18N

        lMusicPlayer.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lMusicPlayer.setForeground(new java.awt.Color(255, 255, 255));
        lMusicPlayer.setText("Music Player");

        bLogIn.setText("LOGIN");

        bSignUp.setText("SIGN-UP");

        lAlreadyHaveAnAccount.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lAlreadyHaveAnAccount.setForeground(new java.awt.Color(255, 255, 255));
        lAlreadyHaveAnAccount.setText("Already have an account?");

        lNewUser.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lNewUser.setForeground(new java.awt.Color(255, 255, 255));
        lNewUser.setText("New user?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lMusicPlayer))
                    .addComponent(lSepotify)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lAlreadyHaveAnAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bLogIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSignUp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(219, 219, 219))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(lNewUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lSepotify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lMusicPlayer)
                .addGap(53, 53, 53)
                .addComponent(lNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lAlreadyHaveAnAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogIn;
    private javax.swing.JButton bSignUp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lAlreadyHaveAnAccount;
    private javax.swing.JLabel lMusicPlayer;
    private javax.swing.JLabel lNewUser;
    private javax.swing.JLabel lSepotify;
    // End of variables declaration//GEN-END:variables
    
    public void addActionListener (ActionListener e) {
        bLogIn.addActionListener(e);
        bSignUp.addActionListener(e);
    }

    public JButton getbLogIn() {
        return bLogIn;
    }

    public JButton getbSignUp() {
        return bSignUp;
    }
}
