/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import java.awt.event.MouseEvent;

/**
 *
 * @author irawan
 */
public class vSignup extends javax.swing.JFrame {

    /**
     * Creates new form vSignup
     */
    public vSignup() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(640, 480);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMaleFemale = new javax.swing.ButtonGroup();
        p1 = new javax.swing.JPanel();
        tfEmail = new javax.swing.JTextField();
        bSignup = new javax.swing.JButton();
        lSepotify = new javax.swing.JLabel();
        bLogin = new javax.swing.JButton();
        tfName = new javax.swing.JTextField();
        rbPerempuan = new javax.swing.JRadioButton();
        rbLaki = new javax.swing.JRadioButton();
        cbBlnLhr = new javax.swing.JComboBox<>();
        cbThnLhr = new javax.swing.JComboBox<>();
        cbTglLhr = new javax.swing.JComboBox<>();
        pfPassword = new javax.swing.JPasswordField();
        lEmail = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        lSignUp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p1.setBackground(new java.awt.Color(51, 51, 51));
        p1.setPreferredSize(new java.awt.Dimension(640, 480));

        tfEmail.setToolTipText("");
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        bSignup.setBackground(new java.awt.Color(0, 255, 51));
        bSignup.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        bSignup.setForeground(new java.awt.Color(0, 204, 51));
        bSignup.setText("Join Sepotify!");
        bSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSignupActionPerformed(evt);
            }
        });

        lSepotify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/iSepotify.png"))); // NOI18N

        bLogin.setText("LOGIN");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        rbPerempuan.setBackground(new java.awt.Color(51, 51, 51));
        bgMaleFemale.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rbPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        rbPerempuan.setText("Female");

        rbLaki.setBackground(new java.awt.Color(51, 51, 51));
        bgMaleFemale.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rbLaki.setForeground(new java.awt.Color(255, 255, 255));
        rbLaki.setText("Male");
        rbLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiActionPerformed(evt);
            }
        });

        cbBlnLhr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        cbThnLhr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));

        cbTglLhr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        pfPassword.setToolTipText("");
        pfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordActionPerformed(evt);
            }
        });

        lEmail.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lEmail.setForeground(new java.awt.Color(255, 255, 255));
        lEmail.setText("Email");

        lPassword.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lPassword.setForeground(new java.awt.Color(255, 255, 255));
        lPassword.setText("Password");

        lName.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lName.setForeground(new java.awt.Color(255, 255, 255));
        lName.setText("Name");

        lSignUp.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lSignUp.setForeground(new java.awt.Color(255, 255, 255));
        lSignUp.setText("Sign-Up");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lEmail)
                            .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(p1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(cbTglLhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbBlnLhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbThnLhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(bSignup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfName)
                                .addComponent(tfEmail)
                                .addComponent(rbPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lPassword)
                            .addComponent(lName)))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(lSepotify)))
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lSignUp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSepotify, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lSignUp)
                .addGap(18, 18, 18)
                .addComponent(lEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbThnLhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTglLhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBlnLhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbLaki)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbPerempuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLogin)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLoginActionPerformed

    private void bSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSignupActionPerformed

    private void rbLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    

    public String getTfEmail() {
        return tfEmail.getText();
    }

    public String getTfName() {
        return tfName.getText();
    }

    public String getPfPassword() {
        return pfPassword.getText();
    }

    /*public JComboBox<String> getCbBlnLhr() {
        return cbBlnLhr;
    }*/
    
    public String getCbTglLhr() {
        int check = cbTglLhr.getSelectedIndex()+1;
        String ret = "";
        switch(check){
            case 1 : ret = "1"; break;
            case 2 : ret = "2"; break;
            case 3 : ret = "3"; break;
            case 4 : ret = "4"; break;
            case 5 : ret = "5"; break;
            case 6 : ret = "6"; break;
            case 7 : ret = "7"; break;
            case 8 : ret = "8"; break;
            case 9 : ret = "9"; break;
            case 10 : ret = "10"; break;
            case 11 : ret = "11"; break;
            case 12 : ret = "12"; break;
            case 13 : ret = "13"; break;
            case 14 : ret = "14"; break;
            case 15 : ret = "15"; break;
            case 16 : ret = "16"; break;
            case 17 : ret = "17"; break;
            case 18 : ret = "18"; break;
            case 19 : ret = "19"; break;
            case 20 : ret = "20"; break;
            case 21 : ret = "21"; break;
            case 22 : ret = "22"; break;
            case 23 : ret = "23"; break;
            case 24 : ret = "24"; break;
            case 25 : ret = "25"; break;
            case 26 : ret = "26"; break;
            case 27 : ret = "27"; break;
            case 28 : ret = "28"; break;
            case 29 : ret = "29"; break;
            case 30 : ret = "30"; break;
            case 31 : ret = "31"; break;
        }
        return ret;
    }
    
    public String get_CbTglLhr(){
        int i = cbTglLhr.getSelectedIndex();
        return cbTglLhr.getItemAt(i);
    }

    /*public JComboBox<String> getCbBlnLhr() {
        return cbTglLhr;
    }*/
    
    public String getCbBlnLhr(){
        int check = cbBlnLhr.getSelectedIndex()+1;
        String ret = "";
        switch(check){
            case 1 : ret = "January"; break;
            case 2 : ret = "February"; break;
            case 3 : ret = "March"; break;
            case 4 : ret = "April"; break;
            case 5 : ret = "May"; break;
            case 6 : ret = "June"; break;
            case 7 : ret = "July"; break;
            case 8 : ret = "August"; break;
            case 9 : ret = "September"; break;
            case 10 : ret = "October"; break;
            case 11 : ret = "November"; break;
            case 12 : ret = "December"; break;
        }
        return ret;
    }
    
    public String get_CbBlnLhr(){
        int i = cbBlnLhr.getSelectedIndex();
        return cbBlnLhr.getItemAt(i);
    }

    /*
    public JComboBox<String> getCbThnLhr() {
        return cbThnLhr;
    }
    */
    
    public String getCbThnLhr() {
        int check = cbThnLhr.getSelectedIndex()+1;
        String ret = "";
        switch(check){
            case 1 : ret = "1945"; break;
            case 2 : ret = "1946"; break;
            case 3 : ret = "1947"; break;
            case 4 : ret = "1948"; break;
            case 5 : ret = "1949"; break;
            case 6 : ret = "1950"; break;
            case 7 : ret = "1951"; break;
            case 8 : ret = "1952"; break;
            case 9 : ret = "1953"; break;
            case 10 : ret = "1954"; break;
            case 11 : ret = "1955"; break;
            case 12 : ret = "1956"; break;
            case 13 : ret = "1957"; break;
            case 14 : ret = "1958"; break;
            case 15 : ret = "1959"; break;
            case 16 : ret = "1960"; break;
            case 17 : ret = "1961"; break;
            case 18 : ret = "1962"; break;
            case 19 : ret = "1963"; break;
            case 20 : ret = "1964"; break;
            case 21 : ret = "1965"; break;
            case 22 : ret = "1966"; break;
            case 23 : ret = "1967"; break;
            case 24 : ret = "1968"; break;
            case 25 : ret = "1969"; break;
            case 26 : ret = "1970"; break;
            case 27 : ret = "1971"; break;
            case 28 : ret = "1972"; break;
            case 29 : ret = "1973"; break;
            case 30 : ret = "1974"; break;
            case 31 : ret = "1975"; break;
            case 32 : ret = "1976"; break;
            case 33 : ret = "1977"; break;
            case 34 : ret = "1978"; break;
            case 35 : ret = "1979"; break;
            case 36 : ret = "1980"; break;
            case 37 : ret = "1981"; break;
            case 38 : ret = "1982"; break;
            case 39 : ret = "1983"; break;
            case 40 : ret = "1984"; break;
            case 41 : ret = "1985"; break;
            case 42 : ret = "1986"; break;
            case 43 : ret = "1987"; break;
            case 44 : ret = "1988"; break;
            case 45 : ret = "1989"; break;
            case 46 : ret = "1990"; break;
            case 47 : ret = "1991"; break;
            case 48 : ret = "1992"; break;
            case 49 : ret = "1993"; break;
            case 50 : ret = "1994"; break;
            case 51 : ret = "1995"; break;
            case 52 : ret = "1996"; break;
            case 53 : ret = "1997"; break;
            case 54 : ret = "1998"; break;
            case 55 : ret = "1999"; break;
            case 56 : ret = "2000"; break;
            case 57 : ret = "2001"; break;
            case 58 : ret = "2002"; break;
            case 59 : ret = "2003"; break;
            case 60 : ret = "2004"; break;
            case 61 : ret = "2005"; break;
            case 62 : ret = "2006"; break;
            case 63 : ret = "2007"; break;
            case 64 : ret = "2008"; break;
            case 65 : ret = "2009"; break;
            case 66 : ret = "2010"; break;
            case 67 : ret = "2011"; break;
            case 68 : ret = "2012"; break;
            case 69 : ret = "2013"; break;
            case 70 : ret = "2014"; break;
            case 71 : ret = "2015"; break;
            case 72 : ret = "2016"; break;
            case 73 : ret = "2017"; break;
            case 74 : ret = "2018"; break;
            case 75 : ret = "2019"; break;
        }
        return ret;
    }
    
    public String get_CbThnLhr(){
        int i = cbThnLhr.getSelectedIndex();
        return cbThnLhr.getItemAt(i);
    }

    public String getRbLaki() {
        return rbLaki.getText();
    }

    public String getRbPerempuan() {
        return rbPerempuan.getText();
    }
    
    public void addActionListener (ActionListener e) {
        bLogin.addActionListener(e);
        bSignup.addActionListener(e);
    }

    public JButton getbLogin() {
        return bLogin;
    }

    public JButton getbSignup() {
        return bSignup;
    }

    public void setCbBlnLhr(JComboBox<String> cbBlnLhr) {
        this.cbBlnLhr = cbBlnLhr;
    }
    

    public void setCbTglLhr(JComboBox<String> cbTglLhr) {
        this.cbTglLhr = cbTglLhr;
    }

    public void setCbThnLhr(JComboBox<String> cbThnLhr) {
        this.cbThnLhr = cbThnLhr;
    }

    public void setPfPassword(String p) {
        pfPassword.setText(p);
    }

    public void setRbLaki(JRadioButton rbLaki) {
        this.rbLaki = rbLaki;
    }

    public void setRbPerempuan(JRadioButton rbPerempuan) {
        this.rbPerempuan = rbPerempuan;
    }

    public void setTfEmail(String e) {
        tfEmail.setText(e);
    }

    public void setTfName(String n) {
        tfName.setText(n);
    }

    public ButtonGroup getBgMaleFemale() {
        return bgMaleFemale;
    }
    
    public String get_BgMaleFemale() {
        if(rbLaki.isSelected()){
            return getRbLaki();
        }else if(rbPerempuan.isSelected()){
            return getRbPerempuan();
        }
        return null;
    }
    
    public void reset(){
        setTfEmail("");
        setPfPassword("");
        setTfName("");
    }

    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bSignup;
    private javax.swing.ButtonGroup bgMaleFemale;
    private javax.swing.JComboBox<String> cbBlnLhr;
    private javax.swing.JComboBox<String> cbTglLhr;
    private javax.swing.JComboBox<String> cbThnLhr;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lSepotify;
    private javax.swing.JLabel lSignUp;
    private javax.swing.JPanel p1;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables

    

}
